### ISSUE TITLE
Add a pen width preview

### ISSUE THREAD

**Issue by dadaa** [dengaku-club/anitize.js#10]
We can change the pen width by a slider.
However, it is not easy to understand the actual width.
To resolve this, we need to add a pen width preview which reflects by the slider.

**Comment by shundroid** [comment]
@dadaa Do you also need to check pen color?
I can also add a feature which checks the color.

**Comment by shundroid** [comment]
@dadaa Wow! It's not easy to show 500px preview.
I don't know how to show it.

I think show real preview on canvas when mousemove, but it's unavailable when touching.

**Comment by shundroid** [comment]
I came up with an idea.
