### ISSUE TITLE
Canvas to store

### ISSUE THREAD

**Issue by shundroid** [dengaku-club/anitize.js#25]
Now, this doesn't support saving state of canvas.

To fix #12 #13 #14 , this issue is necessary.

@dadaa The way to save state is "Vector", right?
Tentatively, I'd like to save "Vector".

**Comment by dadaa** [comment]
I think so. Please keep using Vector.

And, I am undecided which component should keep the history.. It may be better to keep and manage the history by Canvas component.
The reasons are following:
* It seems it's easy to redo/undo without extra communication.
* It seems it's natural to ask the canvas state from frame.

How do you think about?
If we choose above thinking, this action can be dropped.

**Comment by shundroid** [comment]
@dadaa Certainly, The way is the most simple.
It can reduce actions.

However, it's not redux-style.
Are there other components which use the history?
If there are, the history should be managed by store.

How about you?
