### ISSUE TITLE
aspace.js へ送る

### ISSUE THREAD

**Issue by shundroid** [dengaku-club/anitize.js#48]
- タイミングはいつですか

**Comment by dadaa** [comment]
タイミングは、プレビュー再生して、送信ないし共有ボタンを押したらでしょうかね。

aspace.js への送信手順はおそらく以下のようになるんじゃないかと思います。
１．全フレームを描画できる大きな canvas を用意する
２．canvas に各フレームの image を貼り付ける
　　このときフレーム数に応じで x ポジションをずらす
３．canvas.toBlob() メソッドで blob を取る
４．xmlhttprequest で、他の情報(duration やら easing やら) と一緒に送信する。
参考：https://github.com/dengaku-club/aspace.js/blob/develop/samples/post.html

**Comment by shundroid** [comment]
@dadaa ありがとうございます。今 makeJoinedImage.js で、全フレームを描画できる大きな canvas を持っているので、そこで base64url 出力じゃなくて blob 出力するようにすればいいっすかね。
