### ISSUE TITLE
点が打てなくなっている

### ISSUE THREAD

**Issue by dadaa** [dengaku-club/anitize.js#89]
少しでもドラッグしないと描画できない。

**Comment by shundroid** [comment]
あれ、ぼくの環境だと打てます
touch だと打てないんでしょうか

**Comment by dadaa** [comment]
おや？僕のマックでもタブレットでも打てないよ。
打った瞬間はドットが表示されるんだけど、そのあとに残らないといった方が正しいかな。

**Comment by shundroid** [comment]
あれー、なんででしょう
ちょっと今日確認しましょうか
