### ISSUE TITLE
フルスクリーン対応

### ISSUE THREAD

**Issue by dadaa** [dengaku-club/anitize.js#91]

**Comment by dadaa** [comment]
もしかすると UI は要らないかもしれません。
どこかのキーに割り当ててしまうのも手かと思います。
ESC とか？

**Comment by shundroid** [comment]
@dadaa なるほど、でもキーボードってタブレットから呼び出せます？
もし呼び出せなかったら、黒いペンを10回タップしたらフルスクリーンみたいな、
開発者モード的なコマンドにしてもいいかと思いました。
