### ISSUE TITLE
Easing編集画面がタブレット上だと動かない

### ISSUE THREAD

**Issue by dadaa** [dengaku-club/anitize.js#92]
ライブラリがタッチイベントに対応していない？

**Comment by shundroid** [comment]
あらー、そうかもしれないです

**Comment by shundroid** [comment]
してなかったのでさせます

**Comment by shundroid** [comment]
https://github.com/shundroid/bezier-easing-editor

側で、修正しました。
もう一度、npm rm bezier-easing-editor して、install しなおすと、
タッチできるようになっていると思います。
